const coins = require('./coins');

const tests = [
  {
    check: true,
    coin: 'BTC',
    network: 'mainnet',
    mnemonic: 'sudden expire elegant spend they peanut search giggle battle gas sister atom',
    //privateKey: 'L2opBasCx47tgK9h4dP7r9kVRCjyBu7Z47fByBuamYwHYbzbP42g',
    //publicKey: '029f7b0a848819c4e19c2282572a821b0a0dc265128f515af292fc84f81c4b1a3f',
    address: '1P8HdnAAFkJDbbKnfV3721KS9cVyX59x5j',
  },
  {
    check: true,
    coin: 'BTC',
    network: 'testnet',
    mnemonic: 'sudden expire elegant spend they peanut search giggle battle gas sister atom',
    //privateKey: 'cUA5k263Wd8cA6M4StxyJNdrXs4rKk2h88rxATcHunrxaxtpMMXw',
    //publicKey: '02baacab92e5563ca1cb785f412ccf69ef6979d5b6e8b01c01a7e5cc7612051eab',
    address: 'mnkxYF6DZVSeQrQjusHq7xgECTVPp4w24H',
  },
  {
    check: true,
    coin: 'GHOST',
    network: 'testnet',
    mnemonic: 'praise you muffin lion enable neck grocery crumble super myself license ghost',
    address: 'Xa6SpohTZZAKrbqoZjSFkPY34hbCZJy9RG'
  },
  {
    check: true,
    coin: 'NEXT',
    network: 'mainnet',
    mnemonic: 'sudden expire elegant spend they peanut search giggle battle gas sister atom',
    /*
      Account generated by reference node `next-qt`
      > next-qt --usehd=1 --mnemonic="sudden expire elegant spend they peanut search giggle battle gas sister atom"
      File -> Receiving Addresses
    */
    //privateKey: '...', // ?
    //publicKey: '', // ?
    address: 'XJYfa9XF9zYkLkHmQfjvpAEsV2rBiPUB5P', // index 0
    //address 'XX6QMNnYRpks9YzmkFbmpMyHDXzowEJDjc', // index 1
  },
  
]

tests.forEach(test => {
  if (!test.check) {
    return
  }
  console.log('Test mnemonic ⮕ address,', test.coin, test.network)
  account = coins[test.coin][test.network].accountFromMnemonic(test.mnemonic)
  const received = account.address.toString()
  const expected = test.address
  if (received == expected) {
    console.log('OK')
  } else {
    console.log(`(!!!) not OK, expected ${expected}, received ${received}`)
  }
})