import ETH2BTC from './ETH2BTC'
import BTC2ETH from './BTC2ETH'

import LTC2BTC from './LTC2BTC'
import BTC2LTC from './BTC2LTC'

import ETH2LTC from './ETH2LTC'
import LTC2ETH from './LTC2ETH'

import BCH2ETH from './BCH2ETH'
import ETH2BCH from './ETH2BCH'

import EOS2BTC from './EOS2BTC'
import BTC2EOS from './BTC2EOS'

import ETHTOKEN2BTC from './ETHTOKEN2BTC'
import BTC2ETHTOKEN from './BTC2ETHTOKEN'

import QTUM2BTC from './QTUM2BTC'
import BTC2QTUM from './BTC2QTUM'
// import USDT2ETHTOKEN from './USDT2ETHTOKEN'
// import ETHTOKEN2USDT from './ETHTOKEN2USDT'


export {
  ETH2BTC,
  BTC2ETH,

  LTC2BTC,
  BTC2LTC,

  ETH2LTC,
  LTC2ETH,

  BCH2ETH,
  ETH2BCH,

  EOS2BTC,
  BTC2EOS,

  ETHTOKEN2BTC,
  BTC2ETHTOKEN,

  QTUM2BTC,
  BTC2QTUM,

  // USDT2ETHTOKEN,
  // ETHTOKEN2USDT,
}
